# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b82c0420a299222b61de5f5ef2789184367b1c5e03a214a63cc3bbef85a37ba83e800154945edf7ae0f0c08ab586fe0b00bb61c4d35459aafac33ac523a9ee7

test:
  secret_key_base: 2a03bb9720117e82027268eca394989c746d788e1f50aaf0b8d60819e1293bfa56d33121d77d090a6fe8c336bc576a13576fde20f0d860a0457fef18944cfedd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
